name: schedules
description: An app for all schedules

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+2

environment:
    sdk: ">=2.16.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    google_fonts: ^2.3.1
    shared_preferences: ^2.0.13
    feather_icons: ^1.2.0
    url_launcher: ^6.1.0
    provider: ^6.0.2
    path_provider: ^2.0.9
    # flutter_local_notifications: ^9.4.1
    intl: ^0.17.0
    package_info_plus: ^1.4.2
    sentry_flutter: ^6.5.1
    lottie: ^1.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^1.0.0
    flutter_launcher_icons: "^0.9.2"
    msix: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    assets:
        - assets/logo.png
        - assets/loading.json
        - assets/whats-new.json

flutter_icons:
    image_path: assets/logo-square.png
    android: false
    ios: true
    # adaptive_icon_background: assets/adaptive-background.png
    # adaptive_icon_foreground: assets/adaptive-foreground.png

msix_config:
    display_name: Schedules
    publisher_display_name: H. Kamran
    identity_name: com.hkamran.schedules
    install_certificate: false
    capabilities: internetClient
    app_installer:
        publish_folder_path: build/custom/windows/
        hours_between_update_checks: 0
        automatic_background_task: true
        update_blocks_activation: true
        show_prompt: true
        force_update_from_any_version: false
